apiVersion : apps/v1
kind: Deployment 
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name : nodejs
        image: safoueneraddaoui/nodejs-app:v4
        ports:
        -  containerPort: 3000
  replicas: 1
  selector:
    matchLabels:
      app: nodejs  

