apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
    type: mongo-db
spec:
  containers:
  - image: mongo:latest
    name: mongo
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
      protocol: TCP
